### ISSUE TITLE
Add GranuleQuery.collection_id() function

### ISSUE THREAD

**Issue by lewismc** [jddeal/python-cmr#63]
Hi @jddeal we've been using this toolkit... in short _**thank you**_ for publishing it, it;s saved us some time and cleaned up quite a fair bit if code. 
I have a feature request which I would like to discuss with you.
Ideally, we want to search for granules as follows
```
        gq = GranuleQuery()
        gq = gq.collection_id(collection_id)
```
In this user scenario we obtain the collection_id's from the UMM-S = UMM-C associations we curate.

Does adding a function to the GranuleQuery Class make sense?
Thanks

**Comment by jddeal** [comment]
This definitely makes sense to me to add!

Just a quick point of clarification: in your scenario, is collection id referring to the ECHO collection id? Best I can tell from the CMR documentation, concept id might be synonymous with ECHO collection id, but I haven't found a concrete answer from my skimming this evening.

**Comment by lewismc** [comment]
Thanks for the respinse @jddeal 

> is collection id referring to the ECHO collection id?

This is it here
https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#c-concept-id

**Comment by jddeal** [comment]
Gotcha, glad I asked! It looks like ECHO collection id does match concept id for collections (of the handful I checked), but concept id is also used for identifying granules or services. I think I got this squared away and ready for you to take a look at.

I threw a build up on Test PyPI that you can install with `pip install --index-url https://test.pypi.org/simple/ python-cmr`. It includes a new `concept_id(...)` method to both CollectionQuery and GranuleQuery that you can pass one or a list of ID's into. I opted for that name to match what the CMR documentation seems to be favoring for terminology, but it should provide the expected behavior you posted above.

Note: looks like the requests library on Test PyPI is fairly out of date, so you might have to do `pip install --upgrade requests` to eliminate SSL errors at runtime.

Example usages:
```
gq = GranuleQuery()
gq = gq.concept_id("C1299783579-LPDAAC_ECS")  // find granules matching this collection
# gq = gq.concept_id(["G1327299284-LPDAAC_ECS", "G1326330014-LPDAAC_ECS"])  // get these two granules

# not your use case, but this is possible as well
cq = CollectionQuery()
cq = cq.concept_id("C1299783579-LPDAAC_ECS")  // get this collection
# cq = cq.concept_id(["C1299783579-LPDAAC_ECS", "C1441380236-PODAAC"])  // get these two collections
# cq = cq.concept_id("G1327299284-LPDAAC_ECS")  // throws an error, can't search for granule IDs through collections query
```

Implementation notes:
Playing around with CMR, it mentions there are both collection concept id's (prefixed with a C) and granule concept id's (prefixed with a G). For collection searches, they only allow passing in collection concept id's. For granule searches, they support both, but when you pass a collection concept id it's searching for granules associated with that id (which I believe is matching your use case). If you pass granule concept id's it lets you grab specific granule metadata.

**Comment by lewismc** [comment]
This is ideal @jddeal I tried it out and it is exactly what I was thinking of. Thank you

**Comment by jddeal** [comment]
You can grab this off of the official PyPI repos now, version 0.4.1 (includes an unrelated change another user had noticed).

**Comment by lewismc** [comment]
Excellent @jddeal thank you
